import { PolicyRule } from './types';

export const BRAND_VOICE_GUIDELINES = {
  name: "Aurora Cloud Brand Voice",
  values: [
    "Clarity over cleverness",
    "Respect for attention",
    "Earn trust with follow-through",
    "Small teams, taken seriously",
  ],
  pillars: {
    direct: {
      rule: "State the facts and next steps without hedging or unnecessary preambles.",
      goodExample: "Set a deadline.",
      badExample: "You have the ability to configure a deadline.",
    },
    calm: {
      rule: "Maintain a steady, reassuring tone. Avoid hype, alarmism, or false enthusiasm.",
      goodExample: "Task moved to Done.",
      badExample: "Awesome, done!",
    },
    competent: {
      rule: "Clearly explain what occurred, the current state, and the exact next step without jargon or excuses.",
      goodExample: "We initiated a full refund of $49.50 to your original payment method. No action is required.",
      badExample: "Oops! Something went wrong on our server. We hope you understand!",
    },
  },
  formattingRules: [
    "No exclamation marks in product communication or customer messages.",
    "Sentence case throughout; eyebrow labels are the only all-caps use.",
    "Second person ('you', 'your'), never refer to the customer in third person.",
    "Never invent unverified delivery dates, refund timelines, or discount promises.",
    "One clear outcome or call to action per message.",
  ],
};

export const CUSTOMER_SEGMENT_GUIDELINES = {
  "Digital-first": {
    style: "Concise, mobile-first, conversational, straightforward, minimal filler.",
    channelPreferenceWeight: ["WhatsApp", "SMS", "Email"],
    informationDensity: "High density with low word count. Direct links to self-service tracking.",
  },
  "Assisted": {
    style: "Explicit next steps, reassuring context, zero technical jargon, structured reassurance.",
    channelPreferenceWeight: ["Email", "Voice", "WhatsApp"],
    informationDensity: "Step-by-step layout. Clear timeline and direct support reassurance.",
  },
  "Mixed": {
    style: "Balanced tone, clear summary followed by optional detailed link.",
    channelPreferenceWeight: ["WhatsApp", "Email", "SMS"],
    informationDensity: "Moderate context with immediate status.",
  },
};

export const CHANNEL_GUIDELINES = {
  WhatsApp: {
    maxCharacters: 600,
    structure: "1-2 short paragraphs, outcome stated in first sentence, explicit reference/ID, clear CTA or reassurance.",
    greeting: "Friendly but professional (e.g., 'Hello [Name],')",
    signoff: "Aurora Cloud Team",
    permittedElements: ["Plain text", "Bold formatting (*word*)", "Links", "Reference IDs"],
    prohibitions: ["Excessive emojis", "Marketing spam in transactional alerts", "Exclamation marks"],
  },
  SMS: {
    maxCharacters: 160,
    structure: "Ultra-concise, crucial update in first 10 words, reference ID, link or zero-action confirmation.",
    greeting: "None or minimal ([Name]:)",
    signoff: "Aurora Cloud",
    permittedElements: ["Plain text", "Shortened Link", "Numeric IDs"],
    prohibitions: ["Fluff words", "Greetings longer than 4 characters", "Multiple calls to action"],
  },
  Email: {
    maxCharacters: 2000,
    structure: "Subject line (outcome-led), clear status badge, detailed context, next steps list, formal sign-off.",
    greeting: "Dear [Name], / Hi [Name],",
    signoff: "Warm regards,\nAurora Cloud Support",
    permittedElements: ["Structured headings", "Bullet points", "Transaction tables", "Support buttons"],
    prohibitions: ["Clickbait subject lines", "Vague timelines", "Exclamation marks"],
  },
  Voice: {
    maxCharacters: 500,
    structure: "Calm, polite agent script. State caller identity, acknowledge situation, explain resolution, verify comprehension.",
    greeting: "Hello [Name], this is an automated update from Aurora Cloud regarding your recent order.",
    signoff: "Thank you for your patience. Have a good day.",
    permittedElements: ["Phonetic clarity", "Pacing pauses", "Explicit confirmation questions"],
    prohibitions: ["Fast speech", "Unverified claims", "Robotic jargon"],
  },
};

export const COMPANY_POLICIES: PolicyRule[] = [
  {
    id: "POL-TX-001",
    nodePath: "Communication > Transactional > Payment > Payment Successful > Order Failed",
    category: "transactional",
    title: "Payment Captured but Order Creation Failed",
    rule: "When customer payment succeeds but order provisioning fails, immediately reassure the customer, confirm payment capture ID, state that auto-refund has been initiated, and prohibit requesting the customer to retry payment immediately without verification.",
    condition: "event.type == 'payment_successful_order_failed'",
    allowedActions: [
      "Confirm payment capture ID and amount",
      "Confirm refund initiation within standard 3-5 business days banking cycle",
      "Reassure customer no further action is required",
      "Provide customer support escalation link if needed",
    ],
    prohibitedActions: [
      "Do not ask customer to re-enter payment credentials",
      "Do not promise same-day refund unless explicitly authorized",
      "Do not blame third-party gateways without constructive resolution",
    ],
    escalationRequired: false,
    priority: "critical",
  },
  {
    id: "POL-TX-002",
    nodePath: "Communication > Transactional > Payment > Payment Failed",
    category: "transactional",
    title: "Payment Processing Failure",
    rule: "Inform customer of payment failure reason without technical error codes. Provide a secure, direct link to retry payment. Do not retry automatically without consent.",
    condition: "event.type == 'payment_failed'",
    allowedActions: ["Provide retry payment link", "Explain card/bank decline category"],
    prohibitedActions: ["Expose internal gateway trace", "Charge without customer retry"],
    escalationRequired: false,
    priority: "high",
  },
  {
    id: "POL-TX-003",
    nodePath: "Communication > Transactional > Application > Incomplete Application",
    category: "transactional",
    title: "Pending Documents on Application",
    rule: "State exact missing document names, format requirements, upload deadline, and simple 1-step upload link. Avoid bureaucratic language.",
    condition: "event.type == 'application_incomplete'",
    allowedActions: ["List missing document", "Provide direct secure upload link", "State application hold deadline"],
    prohibitedActions: ["Threaten immediate cancellation without grace period", "Request PII over unencrypted email"],
    escalationRequired: false,
    priority: "medium",
  },
  {
    id: "POL-PRV-001",
    nodePath: "Communication > Governance > Privacy & Security",
    category: "privacy",
    title: "Customer PII & Sensitive Data Masking",
    rule: "Never send full credit card numbers, passwords, bank account numbers, or internal database keys in plain text across any channel. Mask credit cards to last 4 digits (e.g. **** 4012).",
    condition: "always",
    allowedActions: ["Mask sensitive identifiers", "Use verified customer first name"],
    prohibitedActions: ["Expose full card numbers", "Send plain-text tokens or internal secrets"],
    escalationRequired: false,
    priority: "critical",
  },
  {
    id: "POL-FAT-001",
    nodePath: "Communication > Governance > Fatigue & Frequency",
    category: "frequency",
    title: "Customer Message Frequency Suppression",
    rule: "If customer has received 2 or more promotional messages in the last 24 hours, all further promotional communications must be SUPPRESSED. If customer has received 3 or more transactional messages today, non-critical transactional messages must be consolidated or suppressed.",
    condition: "customer.recentCommunicationCount24h.promotional >= 2 || customer.recentCommunicationCount24h.transactional >= 3",
    allowedActions: ["Suppress communication with audit log", "Queue for consolidation digest"],
    prohibitedActions: ["Spam customer beyond frequency cap"],
    escalationRequired: false,
    priority: "high",
  },
  {
    id: "POL-FIN-001",
    nodePath: "Communication > Governance > Financial Commitments",
    category: "financial",
    title: "Unauthorized Compensation & Promise Prevention",
    rule: "AI agents are strictly prohibited from inventing discounts, goodwill credits, or compensation amounts above $0 without human supervisor approval. Any compensation offer requires HUMAN APPROVAL.",
    condition: "message.containsCompensation == true",
    allowedActions: ["State standard refund timeline", "Escalate to human supervisor for goodwill credit"],
    prohibitedActions: ["Promise unauthorized goodwill vouchers", "Guarantee bank processing times"],
    escalationRequired: true,
    priority: "critical",
  },
  {
    id: "POL-CONS-001",
    nodePath: "Communication > Governance > Consent Compliance",
    category: "promotional",
    title: "Opt-In Consent Enforcement",
    rule: "Promotional communication is strictly prohibited if customer promotional consent is false. Transactional communication requires transactional consent.",
    condition: "customer.consent == false",
    allowedActions: ["Block message before generation", "Log compliance block"],
    prohibitedActions: ["Send promotional message without verified opt-in"],
    escalationRequired: false,
    priority: "critical",
  },
];
