import { CustomerProfile, BusinessEvent, BusinessObjective } from './types';

export interface PresetScenario {
  id: string;
  name: string;
  tagline: string;
  badge: string;
  customer: CustomerProfile;
  event: BusinessEvent;
  objective: BusinessObjective;
}

export const PRESET_SCENARIOS: PresetScenario[] = [
  {
    id: "hero-rahul",
    name: "Hero: Rahul (Payment Ok / Order Failed)",
    tagline: "Young Digital-first user with 2 previous support tickets experiencing an order creation failure.",
    badge: "Hero Case",
    customer: {
      id: "CUST-90214",
      name: "Rahul Sharma",
      age: 24,
      ageGroup: "18–24",
      segment: "Premium",
      digitalProfile: "Digital-first",
      preferredLanguage: "English",
      preferredChannel: "WhatsApp",
      consent: {
        transactional: true,
        promotional: true,
        voice: false,
      },
      customerValue: "VIP",
      tenureMonths: 18,
      recentCommunicationCount24h: {
        transactional: 1,
        promotional: 0,
      },
      previousSupportContacts: 2,
      sentiment: "Anxious",
      email: "rahul.sharma@example.com",
      phone: "+91 98765 43210",
    },
    event: {
      id: "EVT-88219",
      eventType: "payment_successful_order_failed",
      title: "Payment captured successfully, but inventory allocation failed",
      description: "Customer paid $49.50 (Payment ID: PAY_99482) for Order #ORD-7721, but the inventory microservice timed out and the order was canceled automatically.",
      timestamp: "Just now",
      verifiedFacts: [
        "Payment ID: PAY_99482 ($49.50)",
        "Payment status: Captured",
        "Order #ORD-7721 failed inventory allocation",
        "Automated refund initiated to original card ending in 4012",
        "Refund reference: REF_882103",
      ],
      resolutionStatus: "Refund Initiated",
      transactionId: "PAY_99482",
      orderId: "ORD-7721",
      amount: "$49.50",
    },
    objective: {
      primary: "resolve_issue",
      secondary: "Reduce support contacts and reassure customer",
      customNote: "Acknowledge the payment, confirm the auto-refund with zero customer action required, and reassure that their funds are completely safe.",
    },
  },
  {
    id: "contrasting-meera",
    name: "Contrasting: Meera (Assisted / Document Required)",
    tagline: "Mature Assisted-service customer requiring additional KYC documentation.",
    badge: "Contrasting",
    customer: {
      id: "CUST-33104",
      name: "Meera Patel",
      age: 58,
      ageGroup: "55+",
      segment: "Standard",
      digitalProfile: "Assisted",
      preferredLanguage: "English",
      preferredChannel: "Email",
      consent: {
        transactional: true,
        promotional: false,
        voice: true,
      },
      customerValue: "Medium",
      tenureMonths: 36,
      recentCommunicationCount24h: {
        transactional: 0,
        promotional: 0,
      },
      previousSupportContacts: 0,
      sentiment: "Neutral",
      email: "meera.patel@example.com",
      phone: "+91 98201 12345",
    },
    event: {
      id: "EVT-44012",
      eventType: "application_incomplete",
      title: "Account verification holds pending address proof",
      description: "Application #APP-9921 requires a clear copy of recent utility bill or bank statement to complete address verification.",
      timestamp: "10 mins ago",
      verifiedFacts: [
        "Application ID: APP-9921",
        "Identity verification: Approved",
        "Address verification: Pending document",
        "Accepted documents: Utility bill, Bank statement (under 3 months)",
        "Deadline: October 15, 2026",
      ],
      resolutionStatus: "Requires Customer Action",
      orderId: "APP-9921",
    },
    objective: {
      primary: "complete_application",
      secondary: "Provide step-by-step guidance without technical jargon",
      customNote: "Ensure instructions are explicit and patient. Give phone helpline option if she needs assistance.",
    },
  },
  {
    id: "fatigue-suppression",
    name: "Fatigue: Ananya (Communication Limit Exceeded)",
    tagline: "Customer has already received 3 messages in 24 hours. Evaluates automatic suppression rule.",
    badge: "Suppression Test",
    customer: {
      id: "CUST-77410",
      name: "Ananya Roy",
      age: 29,
      ageGroup: "25–34",
      segment: "Standard",
      digitalProfile: "Digital-first",
      preferredLanguage: "English",
      preferredChannel: "SMS",
      consent: {
        transactional: true,
        promotional: true,
        voice: false,
      },
      customerValue: "Standard",
      tenureMonths: 6,
      recentCommunicationCount24h: {
        transactional: 3,
        promotional: 1,
      },
      previousSupportContacts: 1,
      sentiment: "Frustrated",
      email: "ananya.roy@example.com",
      phone: "+91 91234 56789",
    },
    event: {
      id: "EVT-10029",
      eventType: "service_disruption",
      title: "Routine scheduled server maintenance notice",
      description: "Non-critical cloud storage maintenance scheduled for 02:00 AM UTC with zero expected downtime.",
      timestamp: "5 mins ago",
      verifiedFacts: [
        "Maintenance window: 02:00 AM - 02:30 AM UTC",
        "Impact: Zero anticipated downtime",
        "Severity: Low / Routine",
      ],
      resolutionStatus: "None Required",
    },
    objective: {
      primary: "inform_customer",
      secondary: "Respect customer attention and prevent message fatigue",
    },
  },
  {
    id: "escalation-david",
    name: "Governance: David (Unauthorized Compensation Gate)",
    tagline: "VIP customer with a billing dispute requiring human supervisor approval for goodwill compensation.",
    badge: "Human Approval",
    customer: {
      id: "CUST-11048",
      name: "David Chen",
      age: 42,
      ageGroup: "35–44",
      segment: "High Value",
      digitalProfile: "Mixed",
      preferredLanguage: "English",
      preferredChannel: "Email",
      consent: {
        transactional: true,
        promotional: false,
        voice: true,
      },
      customerValue: "VIP",
      tenureMonths: 48,
      recentCommunicationCount24h: {
        transactional: 1,
        promotional: 0,
      },
      previousSupportContacts: 4,
      sentiment: "Frustrated",
      email: "david.chen@enterprise.com",
      phone: "+1 415 555 0199",
    },
    event: {
      id: "EVT-77294",
      eventType: "customer_complaint",
      title: "Delayed shipment on critical enterprise order with refund & compensation request",
      description: "Order #ENT-5520 was delayed 5 days. Customer requests $150 credit voucher in addition to delivery fee waiver.",
      timestamp: "1 hour ago",
      verifiedFacts: [
        "Order #ENT-5520 delayed by carrier",
        "Delivery fee waiver ($25.00) auto-approved",
        "Additional $150 credit request exceeds auto-allowance ($0.00)",
      ],
      resolutionStatus: "Pending Approval",
      orderId: "ENT-5520",
      amount: "$150.00 Credit Request",
    },
    objective: {
      primary: "retain_customer",
      secondary: "Enforce policy rule POL-FIN-001 (Human supervisor approval for compensation)",
      customNote: "Acknowledge frustration, confirm $25 fee waiver, and route $150 compensation request to human review.",
    },
  },
  {
    id: "contradiction-cross-sell",
    name: "Contradiction: Anti-Cross-Sell Guardrail",
    tagline: "Customer experiences an active transaction failure while brief specifies an aggressive promotional upsell goal.",
    badge: "Contradiction Test",
    customer: {
      id: "CUST-88301",
      name: "Arjun Kapoor",
      age: 28,
      ageGroup: "25–34",
      segment: "High Value",
      digitalProfile: "Digital-first",
      preferredLanguage: "English",
      preferredChannel: "WhatsApp",
      consent: {
        transactional: true,
        promotional: true,
        voice: false,
      },
      customerValue: "VIP",
      tenureMonths: 24,
      recentCommunicationCount24h: {
        transactional: 1,
        promotional: 0,
      },
      previousSupportContacts: 2,
      sentiment: "Anxious",
      email: "arjun.kapoor@example.com",
      phone: "+91 98111 22233",
    },
    event: {
      id: "EVT-99012",
      eventType: "payment_successful_order_failed",
      title: "Payment captured ($149.00) but order inventory allocation timed out",
      description: "Customer paid $149.00 for order #ORD-9901, but the order failed inventory allocation. Auto-refund initiated to card ending 8832.",
      timestamp: "Just now",
      verifiedFacts: [
        "Payment ID: PAY_9901 ($149.00)",
        "Order #ORD-9901 failed inventory allocation",
        "Automated refund initiated to card ending 8832",
        "Refund reference: REF_990122",
      ],
      resolutionStatus: "Refund Initiated",
      transactionId: "PAY_9901",
      orderId: "ORD-9901",
      amount: "$149.00",
    },
    objective: {
      primary: "increase_conversion",
      secondary: "Upsell to Annual Pro tier with 20% discount code",
      customNote: "Promote 20% discount code for annual cloud upgrade during this touchpoint.",
    },
  },
  {
    id: "contradiction-consent-dnd",
    name: "Contradiction: DND Consent Block",
    tagline: "Promotional marketing campaign dispatched to a customer who has explicitly opted out of marketing communications.",
    badge: "Consent Gate",
    customer: {
      id: "CUST-55102",
      name: "Priya Sharma",
      age: 48,
      ageGroup: "45–54",
      segment: "Standard",
      digitalProfile: "Mixed",
      preferredLanguage: "English",
      preferredChannel: "Email",
      consent: {
        transactional: true,
        promotional: false,
        voice: false,
      },
      customerValue: "Standard",
      tenureMonths: 12,
      recentCommunicationCount24h: {
        transactional: 0,
        promotional: 0,
      },
      previousSupportContacts: 0,
      sentiment: "Neutral",
      email: "priya.sharma@example.com",
      phone: "+91 98222 33344",
    },
    event: {
      id: "EVT-33201",
      eventType: "promotional_opportunity",
      title: "Exclusive 30% Cloud Storage Upgrade Campaign",
      description: "Automated seasonal promotional push offering 30% discount on storage renewals.",
      timestamp: "Just now",
      verifiedFacts: [
        "Promotional campaign: STORAGE30",
        "Discount value: 30% off annual plan",
      ],
      resolutionStatus: "None Required",
    },
    objective: {
      primary: "increase_conversion",
      secondary: "Drive immediate upgrade checkout conversions",
    },
  },
];
